### ISSUE TITLE
Option for "reverse" black/white background / foreground text

### ISSUE THREAD

**Issue by whoehenrieder** [cdesjardins/ComBomb#2]
I'd like the option to have a "white" / reverse background with black text instead of the standard black background with white text.
This comes in handy if just taking a screen capture (for documentation ..etc).  The print is much cleaner with the white background.
I don't think it's necessary to get into all sorts of colors - don't think I every used those features on other communication programs.

**Comment by cdesjardins** [comment]
I looked in to it, and it wasn't too bad to integrate this, but it isn't perfect. If you change the background color then you must restart combomb for it to take affect. I tried to make the change take instantly at runtime, but it doesn't look good. Some parts of the screen updated to the new back/fore colors, and some parts didn't depending on how the text was initially rendered. It just looked like crap, so instead of hacking at it for days, I figured this it would be acceptable to just restart the program for this configuration change to take affect. But it is in there now in version 1.20 File->Options->White/Black background radio buttons.
