### ISSUE TITLE
Font sizes over 10pt don't display properly (lower parts of characters chopped off)

### ISSUE THREAD

**Issue by whoehenrieder** [cdesjardins/ComBomb#5]
On font sizes above 10pt, the lower portion of characters can be chopped off when at the bottom of a combomb screen (it displays properly when the line moves up the screen).  Attached example using TERMINAL 12pt font shows how the lower portion of characters such as "gjpqy" or underscore "_" don't display on the last line of the screen.  If you change to 10pt Terminal font, then they display (see example).  This isn't particular to just Terminal font, but I've seen similar issues with other fonts at larger sizes.
![combomb_10pt_terminal-font](https://cloud.githubusercontent.com/assets/10213544/6333844/39cd4018-bb45-11e4-8b0f-1cfdbd690629.jpg)
![combomb_12pt_terminal-font](https://cloud.githubusercontent.com/assets/10213544/6333845/39cd4914-bb45-11e4-805e-30bca8cbad2c.jpg)

**Comment by cdesjardins** [comment]
I am aware of this, and the reason is that when the font changes size the screen does not, it tries to jam as many lines as it can into the screen. In fact this can happen with any font size, all I do is grab the bottom of the screen and resize the window until it fits nicely. I could try and make this a bit smarter, but I personally don't have an issue with the way it currently is considering how trivial the work around is.

The bug report is appreciated however.

**Comment by whoehenrieder** [comment]
Chris - as always, extremely fast response from you.
I actually didn't realize that just resizing the screen eliminated this issue.  I checked on my system and sure enough - that works fine.  I'm closing this issue.
Thanks,
 Werner
